# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: location.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='location.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0elocation.proto\"F\n\x0cLocationItem\x12\x11\n\tperson_id\x18\x02 \x01(\x05\x12\x11\n\tlongitude\x18\x03 \x01(\x02\x12\x10\n\x08latitude\x18\x04 \x01(\x02\"\x07\n\x05\x45mpty\"4\n\x10LocationItemList\x12 \n\tlocations\x18\x01 \x03(\x0b\x32\r.LocationItem2=\n\x11LocationProcessor\x12(\n\x06\x43reate\x12\r.LocationItem\x1a\r.LocationItem\"\x00\x62\x06proto3'
)




_LOCATIONITEM = _descriptor.Descriptor(
  name='LocationItem',
  full_name='LocationItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='person_id', full_name='LocationItem.person_id', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='LocationItem.longitude', index=1,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='LocationItem.latitude', index=2,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=88,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=97,
)


_LOCATIONITEMLIST = _descriptor.Descriptor(
  name='LocationItemList',
  full_name='LocationItemList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='locations', full_name='LocationItemList.locations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=151,
)

_LOCATIONITEMLIST.fields_by_name['locations'].message_type = _LOCATIONITEM
DESCRIPTOR.message_types_by_name['LocationItem'] = _LOCATIONITEM
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['LocationItemList'] = _LOCATIONITEMLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LocationItem = _reflection.GeneratedProtocolMessageType('LocationItem', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONITEM,
  '__module__' : 'location_pb2'
  # @@protoc_insertion_point(class_scope:LocationItem)
  })
_sym_db.RegisterMessage(LocationItem)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'location_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

LocationItemList = _reflection.GeneratedProtocolMessageType('LocationItemList', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONITEMLIST,
  '__module__' : 'location_pb2'
  # @@protoc_insertion_point(class_scope:LocationItemList)
  })
_sym_db.RegisterMessage(LocationItemList)



_LOCATIONPROCESSOR = _descriptor.ServiceDescriptor(
  name='LocationProcessor',
  full_name='LocationProcessor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=153,
  serialized_end=214,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='LocationProcessor.Create',
    index=0,
    containing_service=None,
    input_type=_LOCATIONITEM,
    output_type=_LOCATIONITEM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOCATIONPROCESSOR)

DESCRIPTOR.services_by_name['LocationProcessor'] = _LOCATIONPROCESSOR

# @@protoc_insertion_point(module_scope)
